# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db7ef0abe6bee89cee52ced04b2a0bbfbd820a8f3be7322867e96f94e705dd9799abde0d27c0c5e863cabb20463600695b6a7a77b5a340a3d3e1fc12c99d14b0

test:
  secret_key_base: 6c4522a3913895baa8ac7f9a01a56835e44ffc152c9b6cab031050f5b7bf3345956c045a63061dcd66a22a12d8ff3e9e54b5103f3af0b6754dd332b7bf62bc37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
